database:
  host: localhost
  port: 5432
  name: matchpulse_db
  credentials:
    username: admin
    password: secret123

links:
  nvidia: https://jobs.nvidia.com/careers?query=Software+Development&start=0&location=Seattle%2C++WA%2C++United+States&pid=893393809695&sort_by=timestamp&filter_distance=80&filter_include_remote=1&filter_work_location_option=office%2Cremote&filter_time_type=full+time%2Cpart+time
  google: https://www.google.com/about/careers/applications/jobs/results/?q=Software+Engineer&location=Kirkland%2C+WA%2C+USA&hl=en
  amazon: https://www.amazon.jobs/en/search?offset=0&result_limit=10&sort=relevant&job_type%5B%5D=Full-Time&country%5B%5D=USA&state%5B%5D=Washington&city%5B%5D=Seattle&city%5B%5D=Redmond&city%5B%5D=Bellevue&distanceType=Mi&radius=24km&industry_experience=four_to_six_years&loc_group_id=seattle-metro&latitude=&longitude=&loc_group_id=seattle-metro&loc_query=Greater%20Seattle%20Area%2C%20WA%2C%20United%20States&base_query=software%20engineer&city=&country=&region=&county=&query_options=&
  microsoft: https://apply.careers.microsoft.com/careers?query=Software+Development&start=0&location=United+States%2C+Washington%2C+Redmond&pid=1970393556640555&sort_by=relevance&filter_distance=160&filter_include_remote=1&filter_seniority=Mid-Level
  salesforce: https://careers.salesforce.com/en/jobs/?search=software+development+engineer&country=United+States+of+America&region=Washington&location=Bellevue&location=Remote&location=Seattle&pagesize=20#results
  expedia: https://careers.expediagroup.com/jobs/?keyword=Software+Development+Engineer&&filter[country]=United+States&filter[state]=Washington&filter[city]=Seattle
  oracle: https://careers.oracle.com/en/sites/jobsearch/jobs?keyword=Software+Developer&location=Seattle%2C+WA%2C+United+States&locationId=100000000731910&locationLevel=city&mode=location&radius=25&radiusUnit=KM
  